In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[1]

2

In [6]:
a = np.array([[1,2,3],[4,5,6]])

In [7]:
a[0]

array([1, 2, 3])

In [8]:
a[0][1]

2

In [9]:
a.shape

(2, 3)

In [11]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [18]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
x = np.arange(0, 10,2)
y = np.arange(5)
z = np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [24]:
np.append(x,y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [25]:
np.vstack([x, y, z])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [26]:
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

In [28]:
x

array([0, 2, 4, 6, 8])

In [29]:
y

array([0, 1, 2, 3, 4])

In [30]:
x + y

array([ 0,  3,  6,  9, 12])

In [32]:
x < 2

array([ True, False, False, False, False])

In [33]:
import pandas as pd

In [37]:
s = pd.Series([1, 2, np.nan])

In [38]:
s

0    1.0
1    2.0
2    NaN
dtype: float64

In [39]:
s[0]

1.0

In [40]:
s.sum()

3.0

In [42]:
df = pd.DataFrame({'A':[1, 2], 'B':[3, 4]})

In [43]:
df

A  B
0  1  3
1  2  4

In [46]:
df = pd.DataFrame(np.random.randn(6, 4))
df

0         1         2         3
0 -0.028127  2.347944 -0.269632  1.549931
1  0.546235 -0.570373  0.610549 -0.928464
2 -0.810212 -0.314751 -0.622017 -1.002497
3 -1.567960  1.001496  0.215540  0.755883
4  0.869843 -0.464061 -1.222686 -1.240631
5  0.720124  0.513694 -0.674445  0.413528

In [48]:
df = pd.DataFrame(np.random.randn(6, 4), index=pd.date_range('20230529', periods=6))
df

0         1         2         3
2023-05-29 -1.100305  0.877972  0.942460  0.651701
2023-05-30 -0.606071 -1.601987 -0.741724  0.681250
2023-05-31  1.049810 -0.984853  0.543007  1.668725
2023-06-01 -1.540970 -0.917311  0.681805 -1.182303
2023-06-02 -0.145590 -1.272632 -0.451156  0.431283
2023-06-03 -1.351627  1.960821 -1.985295 -0.035375

In [49]:
df = pd.DataFrame(np.random.randn(6, 4), index=pd.date_range('20230529', periods=6), columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
2023-05-29 -1.037032  0.842239 -0.052414 -0.297150
2023-05-30 -0.409902  1.448219 -0.003517  0.718898
2023-05-31 -1.757233  0.806037  0.081484  0.935362
2023-06-01  1.004906  1.263361  0.009152  0.632351
2023-06-02  0.295000 -1.331769  0.636464 -0.969755
2023-06-03  0.521974  0.990781 -0.702545 -0.081492

In [50]:
df.head(1)

A         B         C        D
2023-05-29 -1.037032  0.842239 -0.052414 -0.29715

In [51]:
df.tail(3)

A         B         C         D
2023-06-01  1.004906  1.263361  0.009152  0.632351
2023-06-02  0.295000 -1.331769  0.636464 -0.969755
2023-06-03  0.521974  0.990781 -0.702545 -0.081492

In [53]:
df.index

DatetimeIndex(['2023-05-29', '2023-05-30', '2023-05-31', '2023-06-01',
               '2023-06-02', '2023-06-03'],
              dtype='datetime64[ns]', freq='D')

In [54]:
df.T

2023-05-29  2023-05-30  2023-05-31  2023-06-01  2023-06-02  2023-06-03
A   -1.037032   -0.409902   -1.757233    1.004906    0.295000    0.521974
B    0.842239    1.448219    0.806037    1.263361   -1.331769    0.990781
C   -0.052414   -0.003517    0.081484    0.009152    0.636464   -0.702545
D   -0.297150    0.718898    0.935362    0.632351   -0.969755   -0.081492

In [55]:
df.sort_values(by='B')

A         B         C         D
2023-06-02  0.295000 -1.331769  0.636464 -0.969755
2023-05-31 -1.757233  0.806037  0.081484  0.935362
2023-05-29 -1.037032  0.842239 -0.052414 -0.297150
2023-06-03  0.521974  0.990781 -0.702545 -0.081492
2023-06-01  1.004906  1.263361  0.009152  0.632351
2023-05-30 -0.409902  1.448219 -0.003517  0.718898

In [56]:
df[0:3]

A         B         C         D
2023-05-29 -1.037032  0.842239 -0.052414 -0.297150
2023-05-30 -0.409902  1.448219 -0.003517  0.718898
2023-05-31 -1.757233  0.806037  0.081484  0.935362

In [59]:
df.loc['20230529']

A   -1.037032
B    0.842239
C   -0.052414
D   -0.297150
Name: 2023-05-29 00:00:00, dtype: float64

In [60]:
df[df > 0]

A         B         C         D
2023-05-29       NaN  0.842239       NaN       NaN
2023-05-30       NaN  1.448219       NaN  0.718898
2023-05-31       NaN  0.806037  0.081484  0.935362
2023-06-01  1.004906  1.263361  0.009152  0.632351
2023-06-02  0.295000       NaN  0.636464       NaN
2023-06-03  0.521974  0.990781       NaN       NaN

In [61]:
df2 = df.copy()
df2['E'] = ['one', 'two', 'three', 'four', 'five', 'six']

In [62]:
df2

A         B         C         D      E
2023-05-29 -1.037032  0.842239 -0.052414 -0.297150    one
2023-05-30 -0.409902  1.448219 -0.003517  0.718898    two
2023-05-31 -1.757233  0.806037  0.081484  0.935362  three
2023-06-01  1.004906  1.263361  0.009152  0.632351   four
2023-06-02  0.295000 -1.331769  0.636464 -0.969755   five
2023-06-03  0.521974  0.990781 -0.702545 -0.081492    six

In [63]:
df.shift(1)

A         B         C         D
2023-05-29       NaN       NaN       NaN       NaN
2023-05-30 -1.037032  0.842239 -0.052414 -0.297150
2023-05-31 -0.409902  1.448219 -0.003517  0.718898
2023-06-01 -1.757233  0.806037  0.081484  0.935362
2023-06-02  1.004906  1.263361  0.009152  0.632351
2023-06-03  0.295000 -1.331769  0.636464 -0.969755

In [64]:
df = pd.DataFrame(np.random.randn(2, 2))

In [65]:
df

0         1
0  0.854284 -0.676794
1 -0.417203  1.830567

In [67]:
pd.concat([df,df])

0         1
0  0.854284 -0.676794
1 -0.417203  1.830567
0  0.854284 -0.676794
1 -0.417203  1.830567

In [68]:
df = pd.DataFrame(np.random.rand(8,4), columns = ['A', 'B', 'C', 'D'])

In [69]:
df

A         B         C         D
0  0.974222  0.920382  0.397204  0.896747
1  0.556069  0.563676  0.141093  0.248480
2  0.497131  0.155494  0.829690  0.243581
3  0.725183  0.595320  0.044698  0.423258
4  0.755469  0.876086  0.060154  0.958160
5  0.074588  0.369937  0.315548  0.596158
6  0.847978  0.487902  0.953976  0.902909
7  0.451872  0.786661  0.192892  0.358130

In [70]:
s = df.iloc[0]
s

A    0.974222
B    0.920382
C    0.397204
D    0.896747
Name: 0, dtype: float64

In [71]:
df.append(s)

/var/folders/pl/l83vr0j523j0hp3dngvsrhqc0000gn/T/ipykernel_22060/1523617293.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(s)


A         B         C         D
0  0.974222  0.920382  0.397204  0.896747
1  0.556069  0.563676  0.141093  0.248480
2  0.497131  0.155494  0.829690  0.243581
3  0.725183  0.595320  0.044698  0.423258
4  0.755469  0.876086  0.060154  0.958160
5  0.074588  0.369937  0.315548  0.596158
6  0.847978  0.487902  0.953976  0.902909
7  0.451872  0.786661  0.192892  0.358130
0  0.974222  0.920382  0.397204  0.896747

In [72]:
df.append(s, ignore_index=True)

/var/folders/pl/l83vr0j523j0hp3dngvsrhqc0000gn/T/ipykernel_22060/4011806271.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(s, ignore_index=True)


A         B         C         D
0  0.974222  0.920382  0.397204  0.896747
1  0.556069  0.563676  0.141093  0.248480
2  0.497131  0.155494  0.829690  0.243581
3  0.725183  0.595320  0.044698  0.423258
4  0.755469  0.876086  0.060154  0.958160
5  0.074588  0.369937  0.315548  0.596158
6  0.847978  0.487902  0.953976  0.902909
7  0.451872  0.786661  0.192892  0.358130
8  0.974222  0.920382  0.397204  0.896747

In [73]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar'], 'B': np.random.randn(4)})

In [74]:
df

A         B
0  foo  1.431709
1  bar -2.108242
2  foo  1.358135
3  bar -0.774564

In [75]:
df.groupby('A').sum()

B
A            
bar -2.882806
foo  2.789845