In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[1]

2

In [6]:
a = np.array([[1,2,3],[4,5,6]])

In [7]:
a[0]

array([1, 2, 3])

In [8]:
a[0][1]

2

In [9]:
a.shape

(2, 3)

In [11]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [18]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
x = np.arange(0, 10,2)
y = np.arange(5)
z = np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [24]:
np.append(x,y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [25]:
np.vstack([x, y, z])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [26]:
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

In [28]:
x

array([0, 2, 4, 6, 8])

In [29]:
y

array([0, 1, 2, 3, 4])

In [30]:
x + y

array([ 0,  3,  6,  9, 12])

In [32]:
x < 2

array([ True, False, False, False, False])